import React, { useState } from "react";
import { MapPin, Store, ShieldCheck, Phone, Navigation, PackageCheck, MessageCircle, GitCompare, Eye, CalendarCheck, Loader2, CheckCircle2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { apiRequest, ApiError } from "../../../utils/api";

export interface AIProductResult {
  id: number; name: string; price: number | string; status: string; store_name: string;
  store_user_id?: number | string | null; store_phone?: string | null; distance?: number | null;
  city?: string | null; province?: string | null; rating?: number | null;
  decision?: { score: number; reasons: string[] };
}
const price = (v: number | string) => { const n = Number(v); return Number.isFinite(n) ? `${new Intl.NumberFormat("fa-IR").format(Math.round(n))} تومان` : `${v} تومان`; };
const distance = (v?: number | null) => v == null || !Number.isFinite(Number(v)) ? null : Number(v) < 1000 ? `${Math.round(Number(v))} متر` : `${(Number(v) / 1000).toFixed(1)} کیلومتر`;

export default React.memo(function ProductResultCard({ product, selected, onToggleCompare }: { product: AIProductResult; selected?: boolean; onToggleCompare?: (product: AIProductResult) => void }) {
  const navigate = useNavigate(); const [busy, setBusy] = useState(false); const [reservationId, setReservationId] = useState<number | null>(null); const [error, setError] = useState("");
  const d = distance(product.distance); const maps = product.store_name ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${product.store_name}${product.city ? ` ${product.city}` : ""}`)}` : null;
  const chat = product.store_user_id ? `/chat/${product.store_user_id}?product=${product.id}` : null;
  const reserve = async () => { setError(""); setBusy(true); try { const r = await apiRequest<{ success: boolean; reservation?: { id: number } }>("/api/reservations", { method: "POST", auth: true, body: { productId: product.id } }); setReservationId(r?.reservation?.id ?? null); } catch (e) { const x = e as ApiError; if (x?.status === 401) { navigate("/login", { state: { returnUrl: "/ai" } }); return; } if (x?.data?.reservationId) setReservationId(Number(x.data.reservationId)); else setError(x?.message || "ثبت درخواست رزرو انجام نشد."); } finally { setBusy(false); } };
  return <article className={`rounded-2xl border bg-white dark:bg-gray-900 p-3 shadow-sm transition-all ${selected ? "border-violet-500 ring-2 ring-violet-500/10" : "border-gray-200 dark:border-gray-700"}`}>
    <div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><h3 className="font-black text-sm text-gray-900 dark:text-white truncate">{product.name}</h3>{product.decision?.score != null && <span className="shrink-0 rounded-full bg-violet-50 dark:bg-violet-500/10 px-2 py-1 text-[9px] font-black text-violet-700 dark:text-violet-300">{product.decision.score}/100</span>}</div><div className="mt-1 flex items-center gap-1.5 text-[10px] text-gray-500 dark:text-gray-400"><Store className="w-3.5 h-3.5" /><span className="truncate">{product.store_name}</span></div></div><div className="text-left shrink-0"><div className="font-black text-sm text-violet-600 dark:text-violet-400">{price(product.price)}</div><div className="mt-1 inline-flex items-center gap-1 text-[9px] font-bold text-emerald-600 dark:text-emerald-400"><PackageCheck className="w-3 h-3" /> {product.status || "موجودی ثبت‌شده"}</div></div></div>
    {product.decision?.reasons?.length ? <div className="mt-2 flex flex-wrap gap-1.5">{product.decision.reasons.slice(0, 3).map(reason => <span key={reason} className="rounded-full bg-gray-50 dark:bg-gray-800 px-2 py-1 text-[9px] font-bold text-gray-600 dark:text-gray-300">✓ {reason}</span>)}</div> : null}
    <div className="mt-3 flex flex-wrap gap-2 text-[9px] font-bold text-gray-500 dark:text-gray-400">{d && <span className="inline-flex items-center gap-1"><MapPin className="w-3 h-3" /> {d}</span>}{product.city && <span>{product.city}</span>}{product.rating != null && <span>★ {Number(product.rating).toFixed(1)}</span>}<span className="inline-flex items-center gap-1 text-emerald-600"><ShieldCheck className="w-3 h-3" /> داده فروشگاه</span></div>
    <div className="mt-3 grid grid-cols-2 gap-2"><button onClick={() => navigate(`/product/${product.id}`)} className="h-9 rounded-xl border border-gray-200 dark:border-gray-700 flex items-center justify-center gap-1.5 text-[10px] font-black text-gray-700 dark:text-gray-200"><Eye className="w-3.5 h-3.5" /> مشاهده کالا</button>{onToggleCompare && <button onClick={() => onToggleCompare(product)} className={`h-9 rounded-xl flex items-center justify-center gap-1.5 text-[10px] font-black ${selected ? "bg-violet-600 text-white" : "border border-violet-200 dark:border-violet-900/50 text-violet-700 dark:text-violet-300"}`}><GitCompare className="w-3.5 h-3.5" /> {selected ? "حذف از مقایسه" : "مقایسه"}</button>}<button onClick={reserve} disabled={busy || reservationId != null} className={`h-9 rounded-xl flex items-center justify-center gap-1.5 text-[10px] font-black ${reservationId != null ? "bg-emerald-600 text-white" : "border border-emerald-200 dark:border-emerald-900/50 text-emerald-700 dark:text-emerald-300"}`}>{busy ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : reservationId != null ? <CheckCircle2 className="w-3.5 h-3.5" /> : <CalendarCheck className="w-3.5 h-3.5" />}{reservationId != null ? "درخواست ثبت شد" : "درخواست رزرو"}</button>{chat && <button onClick={() => navigate(chat)} className="h-9 rounded-xl bg-indigo-600 text-white flex items-center justify-center gap-1.5 text-[10px] font-black"><MessageCircle className="w-3.5 h-3.5" /> گفت‌وگو</button>}{product.store_phone ? <a href={`tel:${product.store_phone}`} className="h-9 rounded-xl border border-gray-200 dark:border-gray-700 flex items-center justify-center gap-1.5 text-[10px] font-black text-gray-700 dark:text-gray-200"><Phone className="w-3.5 h-3.5" /> تماس</a> : <div />}{maps && <a href={maps} target="_blank" rel="noopener noreferrer" className="col-span-2 h-9 rounded-xl bg-violet-600 text-white flex items-center justify-center gap-1.5 text-[10px] font-black"><Navigation className="w-3.5 h-3.5" /> مسیر فروشگاه</a>}</div>
    {reservationId != null && <div className="mt-2 rounded-xl bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-100 dark:border-emerald-500/20 px-3 py-2 text-[9px] font-bold text-emerald-700 dark:text-emerald-300">درخواست ثبت شد؛ رزرو تا تأیید فروشنده قطعی نیست. <button onClick={() => navigate("/messages")} className="mr-1 underline font-black">پیگیری گفتگو</button></div>}{error && <div className="mt-2 rounded-xl bg-rose-50 dark:bg-rose-500/10 border border-rose-100 dark:border-rose-500/20 px-3 py-2 text-[9px] font-bold text-rose-700 dark:text-rose-300">{error}</div>}
  </article>;
});